services:
  mysqldb:
    container_name: mysql-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Chaitu@3105
      MYSQL_DATABASE: productdb
      # MYSQL_USER: klu
      # MYSQL_PASSWORD: klu
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql   # volume added here

  backend:
    image: krishnachaitanya3105/2300031093-exam-backend:final
    container_name: springboot
    ports:
      - "2025:2000"
    depends_on:
      - mysqldb
    restart: on-failure

  frontend:
    image: krishnachaitanya3105/2300031093-exam-frontend:final 
    container_name: react
    ports:
      - "3000:80"
    depends_on:
      - backend

# Declare volumes at the bottom
volumes:
  mysql-data: